from enum import StrEnum


class ErrorCode(StrEnum):
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    CONFLICT = "CONFLICT"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

